/**
 * GENERATED by scripts/sound/prepare-assets.mjs -- do not edit by hand.
 *
 * loop     RMS -20 dBFS; the first `loop` seconds are the seamless cycle.
 * oneshot  peak -1 dBFS; onset at sample zero.
 */

export const ASSETS = {
  "bhakti-ambience": {
    "kind": "loop",
    "loop": 84.0231,
    "channels": 2
  },
  "pandal-night": {
    "kind": "loop",
    "loop": 20.5,
    "channels": 2
  },
  "marigold-petals": {
    "kind": "oneshot",
    "channels": 1
  },
  "ghungroo": {
    "kind": "oneshot",
    "channels": 1
  },
  "bansuri-rise": {
    "kind": "oneshot",
    "channels": 1
  },
  "dhol-knock-1": {
    "kind": "oneshot",
    "channels": 1
  },
  "dhol-knock-2": {
    "kind": "oneshot",
    "channels": 1
  },
  "dhol-knock-3": {
    "kind": "oneshot",
    "channels": 1
  },
  "dhol-roll": {
    "kind": "loop",
    "loop": 7.2,
    "channels": 1
  },
  "coconut-break": {
    "kind": "oneshot",
    "channels": 1
  },
  "diya-light": {
    "kind": "oneshot",
    "channels": 1
  },
  "tabla-pulse": {
    "kind": "loop",
    "loop": 7.3979,
    "channels": 1
  },
  "clay-touch-1": {
    "kind": "oneshot",
    "channels": 1
  },
  "clay-touch-2": {
    "kind": "oneshot",
    "channels": 1
  },
  "clay-touch-3": {
    "kind": "oneshot",
    "channels": 1
  },
  "ghatam-1": {
    "kind": "oneshot",
    "channels": 1
  },
  "ghatam-2": {
    "kind": "oneshot",
    "channels": 1
  },
  "ghatam-3": {
    "kind": "oneshot",
    "channels": 1
  },
  "temple-ghanta": {
    "kind": "oneshot",
    "channels": 1
  },
  "dhol-tasha": {
    "kind": "loop",
    "loop": 72.0011,
    "channels": 2
  },
  "clay-crumble": {
    "kind": "loop",
    "loop": 7.1954,
    "channels": 1
  },
  "gulal-dust": {
    "kind": "oneshot",
    "channels": 1
  },
  "shankh-final": {
    "kind": "oneshot",
    "channels": 2
  },
  "sthapana-music": {
    "kind": "oneshot",
    "channels": 2
  }
} as const;

export type AssetName = keyof typeof ASSETS;
