-- BAPPA 2026 -- the collective, in Postgres.
--
-- Applied with `supabase db push`, or by pasting it into the SQL editor.
-- Either way it is safe to run again: every object is created only if it
-- is missing, so re-running it is a no-op rather than a reset.
--
-- Two ideas do all the work here.
--
-- The first is that an offering's id is its PRIMARY KEY. The id is
-- generated in the browser and reused on every retry of the same
-- submission, so a double click, a refresh mid-send or a network retry
-- collides with a uniqueness constraint instead of being counted twice.
-- The database is doing the deduplication, atomically, rather than the
-- application doing it in two steps and hoping.
--
-- The second is that nothing here knows who anyone is. There is no name,
-- no address, no session and no text: an offering is a type, an
-- intensity, and a seed derived from words that were turned into
-- particles in the browser and discarded in the same breath. The rows are
-- world-readable because there is nothing in them to protect.

-- ------------------------------------------------------------------
-- The tally
-- ------------------------------------------------------------------

-- One row, forever. Offerings take a lock on it as they are counted,
-- which is what makes the count they are stamped with correct under
-- concurrency rather than approximately right.
create table if not exists public.bappa_state (
  id              integer primary key default 1,
  offerings_count integer not null default 0,
  constraint bappa_state_single_row check (id = 1)
);

insert into public.bappa_state (id, offerings_count)
values (1, 0)
on conflict (id) do nothing;

-- ------------------------------------------------------------------
-- The offerings
-- ------------------------------------------------------------------

create table if not exists public.offerings (
  -- Generated by the browser, stable across retries. This being the
  -- primary key IS the duplicate defence.
  id              text primary key,

  -- The order everyone presents them in. Every client plays the same
  -- offerings in the same order because they all sort by this.
  seq             bigserial not null unique,

  type            text not null
                    check (type in ('GRATITUDE', 'WISH', 'VIGHNA', 'PROMISE')),
  intensity       real not null check (intensity >= 0 and intensity <= 1),

  -- A hash of what was written. Shapes the burst so a contribution looks
  -- like itself; the words cannot be recovered from it and never left
  -- the browser to begin with.
  seed            bigint not null,

  -- The tally after this offering. Carried on the row so a client that
  -- misses or repeats an event still lands on the right number, rather
  -- than counting events itself and drifting.
  offerings_count integer not null,

  created_at      timestamptz not null default now()
);

-- No index on seq here: `unique` above already creates one, and adding a
-- second btree on the same column only doubles the write cost of every
-- offering. Dropped rather than left, in case it was created earlier.
drop index if exists public.offerings_seq_idx;

-- ------------------------------------------------------------------
-- Leaving something with him
-- ------------------------------------------------------------------

-- Counting and recording in one statement, so they cannot come apart.
--
-- An id that has been seen before returns the original row untouched:
-- the caller gets the same answer it got the first time, and the tally
-- does not move. This is the whole of the idempotency story.
create or replace function public.leave_offering(
  p_id        text,
  p_type      text,
  p_intensity real,
  p_seed      bigint
)
returns public.offerings
language plpgsql
security definer
set search_path = public
as $$
declare
  result    public.offerings;
  new_count integer;
begin
  select * into result from public.offerings where id = p_id;
  if found then
    return result;
  end if;

  -- Serialises concurrent offerings on the one state row, so the number
  -- each is stamped with is the number it actually produced.
  update public.bappa_state
     set offerings_count = offerings_count + 1
   where id = 1
  returning offerings_count into new_count;

  insert into public.offerings (id, type, intensity, seed, offerings_count)
  values (p_id, p_type, p_intensity, p_seed, new_count)
  on conflict (id) do nothing
  returning * into result;

  -- Another connection with the same id got there between our read and
  -- our write. Give back the number we took and return theirs.
  if result.id is null then
    update public.bappa_state
       set offerings_count = offerings_count - 1
     where id = 1;
    select * into result from public.offerings where id = p_id;
  end if;

  return result;
end;
$$;

-- ------------------------------------------------------------------
-- Abuse
-- ------------------------------------------------------------------

-- The bucket is a salted hash of the address, never the address. A
-- stranger cannot be allowed to finish Bappa on their own and take that
-- from everyone else, but that does not require keeping a record of who
-- anyone is -- and these rows are unreachable from the browser besides.
create table if not exists public.rate_limits (
  bucket     text primary key,
  used       integer not null default 0,
  expires_at timestamptz not null
);

create or replace function public.bump_rate(
  p_bucket  text,
  p_seconds integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  u integer;
begin
  insert into public.rate_limits (bucket, used, expires_at)
  values (p_bucket, 1, now() + make_interval(secs => p_seconds))
  on conflict (bucket) do update
    set used = case
                 when public.rate_limits.expires_at <= now() then 1
                 else public.rate_limits.used + 1
               end,
        -- The window slides from the first hit, not from the last: an
        -- expired window starts again, a live one is not extended.
        expires_at = case
                       when public.rate_limits.expires_at <= now()
                         then now() + make_interval(secs => p_seconds)
                       else public.rate_limits.expires_at
                     end
  returning used into u;
  return u;
end;
$$;

-- ------------------------------------------------------------------
-- Who may do what
-- ------------------------------------------------------------------

alter table public.offerings   enable row level security;
alter table public.bappa_state enable row level security;
alter table public.rate_limits enable row level security;

-- Deliberately NOT `force row level security`. Forcing applies policies
-- to the table owner too, and leave_offering is SECURITY DEFINER so it
-- runs as exactly that -- its insert would then be judged by policies
-- that permit no writes at all, and every offering would fail. The
-- owner is not on the request path anyway: PostgREST arrives as anon,
-- authenticated or service_role, all of which these policies do cover.

-- Anyone may watch. Nobody may write with the public key: every write
-- goes through the server, which is what keeps the state canonical --
-- a browser cannot announce that the tally moved, it can only ask.
drop policy if exists "offerings are public" on public.offerings;
create policy "offerings are public"
  on public.offerings for select
  to anon, authenticated
  using (true);

drop policy if exists "tally is public" on public.bappa_state;
create policy "tally is public"
  on public.bappa_state for select
  to anon, authenticated
  using (true);

-- No policy on rate_limits at all: with RLS on and nothing granted, it
-- is invisible to the public key and reachable only by the service role.

-- Defence in depth. Supabase grants the public keys broad table
-- privileges by default and leaves the policies above to do the gating,
-- which works right up until someone adds a permissive policy in a
-- hurry. Nothing here is ever written by a browser under any policy, so
-- the privilege is taken away as well as the permission.
revoke insert, update, delete, truncate on public.offerings from anon, authenticated;
revoke insert, update, delete, truncate on public.bappa_state from anon, authenticated;
revoke all on public.rate_limits from anon, authenticated;

-- These two run as their owner and so bypass every policy above. Left
-- reachable they would be a way for anyone holding the public key to
-- write to the collective through PostgREST -- no server, no rate limit,
-- and no closed window on the last day.
--
-- FROM PUBLIC is the part that matters, and is easy to get wrong:
-- Postgres grants EXECUTE on a new function to PUBLIC, and anon inherits
-- it. Revoking from anon and authenticated alone leaves that grant in
-- place and the door open. Tested, because reading it is not enough.
revoke all on function public.leave_offering(text, text, real, bigint)
  from public, anon, authenticated;
revoke all on function public.bump_rate(text, integer)
  from public, anon, authenticated;

-- Which leaves the server, which is the point.
grant execute on function public.leave_offering(text, text, real, bigint) to service_role;
grant execute on function public.bump_rate(text, integer) to service_role;

-- ------------------------------------------------------------------
-- Realtime
-- ------------------------------------------------------------------

-- What replaces polling. Clients hold one socket to Supabase and are
-- pushed each new row; watching costs nothing until something happens.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
     where pubname = 'supabase_realtime'
       and schemaname = 'public'
       and tablename = 'offerings'
  ) then
    alter publication supabase_realtime add table public.offerings;
  end if;
end
$$;
